import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  output: "standalone",
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
  },
  async rewrites() {
    return [
      { source: "/aiz-uploader/upload", destination: "/api/uploader" },
      { source: "/track-your-order", destination: "/track-order" },
      { source: "/users/login", destination: "/login" },
      { source: "/users/registration", destination: "/register" },
      { source: "/password/reset", destination: "/forgot-password" },
      { source: "/deliveryboy/login", destination: "/delivery-boy/login" },
      { source: "/all-flash-deals", destination: "/flash-deals" },
      { source: "/inhouse-products", destination: "/inhouse" },
      { source: "/wallet_recharge_success", destination: "/wallet-recharge-success" },
      { source: "/re-order/:id", destination: "/dashboard/purchase-history" },
      { source: "/admin/all_orders", destination: "/admin/orders" },
      { source: "/admin/inhouse-orders", destination: "/admin/orders" },
      { source: "/admin/seller_orders", destination: "/admin/orders" },
      { source: "/admin/general-setting", destination: "/admin/settings" },
      { source: "/admin/payment-method", destination: "/admin/settings/payments" },
      { source: "/admin/social-login", destination: "/admin/settings/social-login" },
      { source: "/admin/smtp-settings", destination: "/admin/settings/smtp" },
      { source: "/admin/brand", destination: "/admin/brands" },
      { source: "/admin/category", destination: "/admin/categories" },
      { source: "/admin/roles", destination: "/admin/staffs" },
      { source: "/admin/all-file", destination: "/admin/uploaded-files" },
      { source: "/admin/file_system", destination: "/admin/settings/file-system" },
      { source: "/admin/business-settings/thermal-printer-config", destination: "/admin/settings/thermal-printer" },
      { source: "/admin/thermal-printer", destination: "/admin/settings/thermal-printer" },
      { source: "/admin/google-recaptcha", destination: "/admin/settings/third-party" },
      { source: "/admin/google-analytics", destination: "/admin/settings/third-party" },
      { source: "/admin/google-map", destination: "/admin/settings/third-party" },
      { source: "/admin/google-firebase", destination: "/admin/settings/third-party" },
      { source: "/admin/google-tag-manager", destination: "/admin/settings/third-party" },
      { source: "/admin/facebook_pixel", destination: "/admin/settings/third-party" },
      { source: "/admin/facebook-comment", destination: "/admin/settings/third-party" },
      { source: "/admin/pixel-analytics/configuration", destination: "/admin/settings/third-party" },
      { source: "/admin/shipping_configuration", destination: "/admin/settings/shipping" },
      { source: "/admin/support_ticket", destination: "/admin/support-tickets" },
      { source: "/seller/money-withdraw-requests", destination: "/seller/payouts" },
      { source: "/seller/support_ticket", destination: "/seller/support" },
      { source: "/seller/shop/apply-for-verification", destination: "/seller/verify" },
      { source: "/seller/categories-wise-product-discount", destination: "/seller/category-discount" },
      { source: "/seller/category-wise-commission", destination: "/seller/category-commission" },
      { source: "/seller/note/index", destination: "/seller/notes" },
      { source: "/seller/note/create", destination: "/seller/notes" },
      { source: "/seller/uploads", destination: "/seller/uploaded-files" },
      { source: "/seller/refund-request", destination: "/seller/refund-requests" },
      { source: "/seller/vendor_refund_request", destination: "/seller/refund-requests" },
      { source: "/seller/refund-configuration", destination: "/seller/refund-requests" },
      { source: "/assigned-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/pickup-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/on-the-way-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/completed-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/pending-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/cancelled-deliveries", destination: "/delivery-boy/dashboard" },
      { source: "/total-collections", destination: "/delivery-boy/dashboard" },
      { source: "/total-earnings", destination: "/delivery-boy/dashboard" },
      { source: "/cancel-request-list", destination: "/delivery-boy/dashboard" },
      { source: "/affiliate/user", destination: "/affiliate" },
      { source: "/admin/refund-request-all", destination: "/admin/refund-requests" },
      { source: "/admin/dispute-refund-request-all", destination: "/admin/refund-requests" },
      { source: "/admin/refund-request-config", destination: "/admin/refund-requests" },
      { source: "/admin/refund-reason-index", destination: "/admin/refund-requests" },
      { source: "/admin/categories-wise-product-refund", destination: "/admin/refund-requests" },
      { source: "/refund-request/:id", destination: "/dashboard/refund-requests" },
      { source: "/dispute-refund-request/:id", destination: "/dashboard/refund-requests" },
      { source: "/admin/affiliate/withdraw_requests", destination: "/admin/affiliate/withdraw-requests" },
      { source: "/admin/auction_products-orders", destination: "/admin/auction/orders" },
      { source: "/admin/auction-product/create", destination: "/admin/auction/products" },
      { source: "/preorder-product/:slug", destination: "/product/:slug" },
      { source: "/preorder/product/:slug", destination: "/product/:slug" },
      { source: "/admin/wholesale-product/create", destination: "/admin/products/create" },
      { source: "/seller/wholesale-product/create", destination: "/seller/products/create" },
      { source: "/admin/club-points/configuration", destination: "/admin/club-points" },
      { source: "/admin/club-points/index", destination: "/admin/club-points" },
      { source: "/admin/set-club-points", destination: "/admin/club-points" },
      { source: "/admin/pathao-configuration", destination: "/admin/settings/couriers" },
      { source: "/admin/steadfast-configuration", destination: "/admin/settings/couriers" },
      { source: "/admin/shiprocket-configuration", destination: "/admin/settings/couriers" },
      { source: "/admin/redx-configuration", destination: "/admin/settings/couriers" },
      { source: "/admin/website/appearance", destination: "/admin/settings/appearance" },
      { source: "/admin/website/header", destination: "/admin/settings/appearance" },
      { source: "/admin/website/footer", destination: "/admin/settings/appearance" },
      { source: "/admin/website/pages", destination: "/admin/website-settings/pages" },
      { source: "/admin/custom-pages", destination: "/admin/website-settings/pages" },
      { source: "/admin/manual_payment_methods", destination: "/admin/settings/payments" },
      { source: "/admin/brand-bulk-upload", destination: "/admin/brands/bulk-upload" },
      { source: "/admin/measurement-points", destination: "/admin/products/measurement-points" },
      { source: "/admin/todays-deal-products-index", destination: "/admin/promotional-products-index" },
      { source: "/admin/top-bar-setting", destination: "/admin/website-settings/top-bar" },
      { source: "/admin/top-bar-list", destination: "/admin/website-settings/top-bar" },
      { source: "/admin/top-bar-create", destination: "/admin/website-settings/top-bar" },
      { source: "/admin/pickup-address-list", destination: "/admin/settings/pickup-addresses" },
      { source: "/admin/pickup-address-create", destination: "/admin/settings/pickup-addresses" },
      { source: "/admin/shipping-box-size-list", destination: "/admin/settings/box-sizes" },
      { source: "/admin/shipping-box-size-create", destination: "/admin/settings/box-sizes" },
      { source: "/admin/marketing-dashboard", destination: "/admin/marketing/analytics" },
      { source: "/admin/marketing-analytics-dashboard", destination: "/admin/marketing/analytics" },
      { source: "/admin/promotion-and-offers-dashboard", destination: "/admin/promotional-products-index" },
      { source: "/admin/product-management/dashboard", destination: "/admin/products" },
      { source: "/403", destination: "/forbidden" },
    ]
  },
}

export default nextConfig
